version = 1

version = 1

test_patterns = ["test/**", "tests/**"]
exclude_patterns = [
  "lib/generated/**",
  "build/**",
  "**/*.g.dart",
  "**/*.freezed.dart"
]

[[analyzers]]
name = "dart"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x" # adjust to your Dart version

  [analyzers.options]
  report_level = "warning" # downgrade all issues to warnings

  # Optional: Ignore specific rules completely
  ignore_patterns = [
    "prefer_const_constructors",
    "avoid_print",
    "non_constant_identifier_names",
    "unused_import",
    "file_names"
  ]

[[analyzers]]
name = "dart-analyze"
type = "community"