name: delivoo
description: A new Flutter application.

version: 2.0.2+75

environment:
  sdk: 3.6.2

dependencies:
  animation_wrappers: ^3.0.0
  app_settings: ^5.1.1
  avatar_glow: ^3.0.1
  background_location: ^0.13.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.0
  confetti: ^0.8.0
  country_code_picker: ^3.1.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  firebase_analytics: ^11.3.6
  firebase_core: ^3.9.0
  firebase_crashlytics: ^4.2.0
  firebase_messaging: ^15.1.6
  fl_country_code_picker: ^0.1.9+1
  flutter:
    sdk: flutter
  #  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.1.6
  flutter_emoji_feedback: ^1.0.3
  flutter_feather_icons: ^2.0.0+1
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_phoenix: ^1.1.1
  flutter_polyline_points: ^2.1.0
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.8.0
  geocoding: ^3.0.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.0
  #  http: ^1.2.2
  intl: ^0.20.1
  location: ^7.0.1
  lottie: ^3.3.0
  new_version_plus: ^0.0.12
  #  payu_checkoutpro_flutter: ^1.0.4
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  place_picker: ^0.10.0
  #  flutter_osm_plugin: ^1.3.6
  platform_device_id_plus: ^1.0.6
  provider: ^6.1.2
  razorpay_flutter: ^1.3.7
  flutter_regex: ^0.0.3
  share_plus: ^10.1.3
  shared_preferences: ^2.3.5
  timeline_tile: ^2.0.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  dropdown_button2: ^2.3.9
  flutter_easyloading: ^3.0.5
  mappls_gl: ^1.1.2
  mappls_place_widget: ^1.0.2
  restart_app: ^1.3.2

dependency_overrides:
  http: ^1.2.2
  intl: ^0.20.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter
  shimmer: ^3.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "images/logos/alphaexpress_app_symbol.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - images/
    - images/account/
    - images/address/
    - images/custom/
    - images/footermenu/
    - images/icons/
    - images/logos/
    - images/maincategory/
    - images/veg/
    - images/veg/Sellers/
    - images/veg/Vegetables/
    - images/payment/
    - assets/applied.json