// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB40gFLlmWczEzQKWrb--tEXIbhdzwIS-Q',
    appId: '1:145459629698:web:41e5faebd480c1dcf2ee9b',
    messagingSenderId: '145459629698',
    projectId: 'alphaexpress-e9cec',
    authDomain: 'alphaexpress-e9cec.firebaseapp.com',
    storageBucket: 'alphaexpress-e9cec.firebasestorage.app',
    measurementId: 'G-FDYMKJXZEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBArbGx2MkrZlLMHTni5v2zQTZEfuRzbvU',
    appId: '1:145459629698:android:755b31efdb7f2287f2ee9b',
    messagingSenderId: '145459629698',
    projectId: 'alphaexpress-e9cec',
    storageBucket: 'alphaexpress-e9cec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsYmrCi74nRbtOg7x_GF8Ihp_6uIOaGNs',
    appId: '1:145459629698:ios:40b64b62ba1e2800f2ee9b',
    messagingSenderId: '145459629698',
    projectId: 'alphaexpress-e9cec',
    storageBucket: 'alphaexpress-e9cec.firebasestorage.app',
    iosClientId: '145459629698-gu053qinsree1oboretivt7lk1mtvfs6.apps.googleusercontent.com',
    iosBundleId: 'com.kisanserv.express',
  );
}
