name: Scan with dart-analyze

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Run Dart Analyze
        run: dart analyze > dart_analyze.txt || true

      - name: Dart Analyze to SARIF
        uses: advanced-security/dart-analyzer-sarif@main
        with:
          input: dart_analyze.txt
          output: dart_analyze.sarif

      # ✅ This ensures GitHub sees the SARIF file
      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: dart_analyze.sarif

      - name: Upload SARIF report to DeepSource
        run: |
          curl https://deepsource.io/cli | sh
          ./bin/deepsource report --analyzer dart-analyze --analyzer-type community --value-file ./dart_analyze.sarif
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
